<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReasonSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('reasons')->insert([
            ["name" => "Abuso Sexual"],
            ["name" => "Adolescência"],
            ["name" => "Adoção de Filhos"],
            ["name" => "Agressividade"],
            ["name" => "Alterações de Humor"],
            ["name" => "Angústia"],
            ["name" => "Anorexia"],
            ["name" => "Ansiedade"],
            ["name" => "Assertividade"],
            ["name" => "Assédio Moral"],
            ["name" => "Autismo"],
            ["name" => "Auto Mutilação"],
            ["name" => "Autoconhecimento"],
            ["name" => "Autoestima"],
            ["name" => "Avaliação de Perfil Profissional e Vocacional"],
            ["name" => "Borderline"],
            ["name" => "Bulimia"],
            ["name" => "Bullying rtunação"],
            ["name" => "Burnout"],
            ["name" => "Cirurgia Bariátrica"],
            ["name" => "Ciúmes"],
            ["name" => "Claustrofobia"],
            ["name" => "Compulsão Alimentar"],
            ["name" => "Controle ligência Emocional"],
            ["name" => "Criatividade"],
            ["name" => "Culpa"],
            ["name" => "Câncer"],
            ["name" => "Deficiência Física"],
            ["name" => "Depressão"],
            ["name" => "Desenvolvimento nça de Carreira"],
            ["name" => "Desmotivação Profissional"],
            ["name" => "Dislexia"],
            ["name" => "Diversidade"],
            ["name" => "Doenças"],
            ["name" => "Doenças Emocionais ças Mentais"],
            ["name" => "Dor"],
            ["name" => "Educação Financeira"],
            ["name" => "Empatia"],
            ["name" => "Empoderamento"],
            ["name" => "Esportes idades Físicas"],
            ["name" => "Esquizofrenia"],
            ["name" => "Estresse"],
            ["name" => "Estudos e Aprendizados"],
            ["name" => "Excesso de peso"],
            ["name" => "Falta de Desejo"],
            ["name" => "Falta de Prazer"],
            ["name" => "Felicidade"],
            ["name" => "Filhos rnidade e Maternidade"],
            ["name" => "Foco"],
            ["name" => "Gratidão"],
            ["name" => "Gravidez"],
            ["name" => "HIV"],
            ["name" => "Habilidades de Liderança"],
            ["name" => "Ideação Suicida as Suicidas"],
            ["name" => "Intolerância Religiosa"],
            ["name" => "LGBTQIAPN+ tidade de Gênero ssexual sgênero"],
            ["name" => "Meditação fulness"],
            ["name" => "Medo de Dirigir"],
            ["name" => "Medo de Falar em Público"],
            ["name" => "Medos e Fobias"],
            ["name" => "Menopausa"],
            ["name" => "Morte e Luto"],
            ["name" => "Motivação"],
            ["name" => "Mudança de Estilo de Vida"],
            ["name" => "Mudança de País nça de Estado nça de Cidade"],
            ["name" => "Obesidade"],
            ["name" => "Obsessão"],
            ["name" => "Orientação Sexual"],
            ["name" => "Paciência"],
            ["name" => "Perfeccionismo"],
            ["name" => "Personalidade Antissocial"],
            ["name" => "Preconceito LGBTQIAPN+"],
            ["name" => "Problemas Financeiros"],
            ["name" => "Procrastinação"],
            ["name" => "Propósito de Vida"],
            ["name" => "Racismo"],
            ["name" => "Raiva"],
            ["name" => "Redes Sociais"],
            ["name" => "Relacionamentos litos Amorosos es"],
            ["name" => "Relacionamentos litos Familiares"],
            ["name" => "Relacionamentos Profissionais"],
            ["name" => "Relacionamentos com Amigos"],
            ["name" => "Resiliência"],
            ["name" => "Sexualidade"],
            ["name" => "Sono"],
            ["name" => "Síndrome do Pânico"],
            ["name" => "Terapia de Casal mento"],
            ["name" => "Terceira Idade"],
            ["name" => "Timidez"],
            ["name" => "Transtorno Bipolar"],
            ["name" => "Transtorno Obsessivo Compulsivo (TOC)"],
            ["name" => "Transtorno de Déficit de Atenção e Hiperatividade (TDAH)"],
            ["name" => "Transtorno de Estresse Pós-Traumatico (TEPT)"],
            ["name" => "Transtorno de Personalidade"],
            ["name" => "Transtornos Alimentares"],
            ["name" => "Traumas e Abusos"],
            ["name" => "Tripofobia"],
            ["name" => "Violência Doméstica"],
            ["name" => "Vícios"],
            ["name" => "Xenofobia"],
        ]);
    }
}
