#!/bin/sh

# Cores
NC='\033[0m'
BRed='\033[1;31m'

REGEX_ISSUE_ID="[a-zA-Z0-9._-]+-[0-9]+"
BRANCH_NAME=$(git symbolic-ref --short HEAD)
ISSUE_ID=$(echo "$BRANCH_NAME" | grep -o -E "$REGEX_ISSUE_ID")
COMMIT_MESSAGE=$(cat "$1")

if [ -z "$ISSUE_ID" ]; then
    echo -e "${BRed}Branch não está no padrão que deveria, mestre...${NC}"
    exit 1
fi

# Se já começa com o issue id, tudo certo
if echo "$COMMIT_MESSAGE" | grep -q "^$ISSUE_ID"; then
    exit 0
fi

# Corrige a mensagem e salva
echo "$ISSUE_ID: $COMMIT_MESSAGE" > "$1"
exit 0